<?php

namespace ABMBundle\Repository;

/**
 * LicenciasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LicenciasRepository extends \Doctrine\ORM\EntityRepository
{
}
