<?php

namespace ABMBundle\Repository;

/**
 * PrepagaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrepagaRepository extends \Doctrine\ORM\EntityRepository
{
}
