<?php

namespace ABMBundle\Repository;

/**
 * VacacionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VacacionesRepository extends \Doctrine\ORM\EntityRepository
{
}
